/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mdsproject.front;

import com.sun.org.apache.xml.internal.security.exceptions.Base64DecodingException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mdsproject.dao.UsuarioDao;

/**
 *
 * @author jhordangabriel
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();
        panelCadastrar = new javax.swing.JPanel();
        labelCadastroUsuarios = new javax.swing.JLabel();
        nomeUsuaLbl = new javax.swing.JLabel();
        nomeUsuaTf = new javax.swing.JTextField();
        SenhaUsuaLbl = new javax.swing.JLabel();
        senhaUsuaPf = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tipoUsuaCb = new javax.swing.JComboBox<>();
        salvarUsuaBtn = new javax.swing.JButton();
        limparUsuaBtn = new javax.swing.JButton();
        panelListarUsuarios = new javax.swing.JPanel();
        labelListaUsuarios = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuaTa = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        localizarNav = new javax.swing.JMenu();
        controleNav = new javax.swing.JMenu();
        arquivosNav = new javax.swing.JMenu();
        cadastrarNav = new javax.swing.JMenuItem();
        listarNav = new javax.swing.JMenuItem();
        editarNav = new javax.swing.JMenuItem();
        removerNav = new javax.swing.JMenuItem();
        avaliarNav = new javax.swing.JMenuItem();
        usuariosNav = new javax.swing.JMenu();
        cadastrarUsuaNav = new javax.swing.JMenuItem();
        listarUsuaNav = new javax.swing.JMenuItem();
        sairNav = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());

        panelCadastrar.setBackground(new java.awt.Color(255, 255, 255));

        labelCadastroUsuarios.setText("Cadastro de Usuários");

        nomeUsuaLbl.setText("Nome");

        SenhaUsuaLbl.setText("Senha");

        jLabel1.setText("Tipo");

        tipoUsuaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Professor" }));

        salvarUsuaBtn.setText("Salvar");
        salvarUsuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarUsuaBtnActionPerformed(evt);
            }
        });

        limparUsuaBtn.setText("Limpar");
        limparUsuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparUsuaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCadastrarLayout = new javax.swing.GroupLayout(panelCadastrar);
        panelCadastrar.setLayout(panelCadastrarLayout);
        panelCadastrarLayout.setHorizontalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarLayout.createSequentialGroup()
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(labelCadastroUsuarios))
                            .addGroup(panelCadastrarLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                                        .addComponent(limparUsuaBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(salvarUsuaBtn))
                                    .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1)
                                        .addComponent(nomeUsuaLbl)
                                        .addComponent(SenhaUsuaLbl)
                                        .addComponent(nomeUsuaTf)
                                        .addComponent(senhaUsuaPf)
                                        .addComponent(tipoUsuaCb, 0, 359, Short.MAX_VALUE)))))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(panelCadastrarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        panelCadastrarLayout.setVerticalGroup(
            panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroUsuarios)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhaUsuaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senhaUsuaPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoUsuaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarUsuaBtn)
                    .addComponent(limparUsuaBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelContent.add(panelCadastrar, "card2");

        panelListarUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        labelListaUsuarios.setText("Lista de Usuários");

        listaUsuaTa.setColumns(20);
        listaUsuaTa.setRows(5);
        jScrollPane1.setViewportView(listaUsuaTa);

        javax.swing.GroupLayout panelListarUsuariosLayout = new javax.swing.GroupLayout(panelListarUsuarios);
        panelListarUsuarios.setLayout(panelListarUsuariosLayout);
        panelListarUsuariosLayout.setHorizontalGroup(
            panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                .addGroup(panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(labelListaUsuarios))
                    .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelListarUsuariosLayout.setVerticalGroup(
            panelListarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelListaUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContent.add(panelListarUsuarios, "card2");

        jPanel1.add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        localizarNav.setText("Localizar");
        jMenuBar1.add(localizarNav);

        controleNav.setText("Controle");

        arquivosNav.setText("Arquivos");

        cadastrarNav.setText("Cadastrar");
        arquivosNav.add(cadastrarNav);

        listarNav.setText("Listar");
        arquivosNav.add(listarNav);

        editarNav.setText("Editar");
        arquivosNav.add(editarNav);

        removerNav.setText("Remover");
        removerNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerNavActionPerformed(evt);
            }
        });
        arquivosNav.add(removerNav);

        avaliarNav.setText("Avaliar");
        arquivosNav.add(avaliarNav);

        controleNav.add(arquivosNav);

        usuariosNav.setText("Usuários");

        cadastrarUsuaNav.setText("Cadastrar");
        cadastrarUsuaNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuaNavActionPerformed(evt);
            }
        });
        usuariosNav.add(cadastrarUsuaNav);

        listarUsuaNav.setText("Listar");
        listarUsuaNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuaNavActionPerformed(evt);
            }
        });
        usuariosNav.add(listarUsuaNav);

        controleNav.add(usuariosNav);

        jMenuBar1.add(controleNav);

        sairNav.setText("Sair");
        jMenuBar1.add(sairNav);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarUsuaNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuaNavActionPerformed
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelCadastrar);
        panelContent.repaint();
        panelContent.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarUsuaNavActionPerformed

    private void listarUsuaNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUsuaNavActionPerformed
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelListarUsuarios);
        panelContent.repaint();
        panelContent.revalidate();
        
        try {
            String lista = UsuarioDao.listar();
            listaUsuaTa.setText(lista);
            listaUsuaTa.setEditable(false);
            // TODO add your handling code here:
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Base64DecodingException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_listarUsuaNavActionPerformed

    private void removerNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerNavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerNavActionPerformed

    private void limparUsuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparUsuaBtnActionPerformed
        nomeUsuaTf.setText("");
        senhaUsuaPf.setText("");
    }//GEN-LAST:event_limparUsuaBtnActionPerformed

    private void salvarUsuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarUsuaBtnActionPerformed
        String nome = nomeUsuaTf.getText();
        String senha = senhaUsuaPf.getText();
        int type = tipoUsuaCb.getSelectedIndex();
        
        if(!nome.isEmpty() && !senha.isEmpty()){
            try {
                UsuarioDao.cadastrar(nome, senha, type);
            } catch (IOException ex) {
                Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Usuário " + nome + " cadastrado com sucesso!");
            nomeUsuaTf.setText("");
            senhaUsuaPf.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ocorreu um erro! Favor preencha todos os campos.");
        }
    }//GEN-LAST:event_salvarUsuaBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SenhaUsuaLbl;
    private javax.swing.JMenu arquivosNav;
    private javax.swing.JMenuItem avaliarNav;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem cadastrarNav;
    private javax.swing.JMenuItem cadastrarUsuaNav;
    private javax.swing.JMenu controleNav;
    private javax.swing.JMenuItem editarNav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCadastroUsuarios;
    private javax.swing.JLabel labelListaUsuarios;
    private javax.swing.JButton limparUsuaBtn;
    private javax.swing.JTextArea listaUsuaTa;
    private javax.swing.JMenuItem listarNav;
    private javax.swing.JMenuItem listarUsuaNav;
    private javax.swing.JMenu localizarNav;
    private javax.swing.JLabel nomeUsuaLbl;
    private javax.swing.JTextField nomeUsuaTf;
    private javax.swing.JPanel panelCadastrar;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelListarUsuarios;
    private javax.swing.JMenuItem removerNav;
    private javax.swing.JMenu sairNav;
    private javax.swing.JButton salvarUsuaBtn;
    private javax.swing.JPasswordField senhaUsuaPf;
    private javax.swing.JComboBox<String> tipoUsuaCb;
    private javax.swing.JMenu usuariosNav;
    // End of variables declaration//GEN-END:variables
}
